package com.becarios.proyecto_definitivo.model.itr;
// Generated 22-mar-2017 16:09:41 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Itr generated by hbm2java
 */
@Entity
@Table(name = "itr", catalog = "HE")
public class Itr implements java.io.Serializable {

	private int idProyecto;
	private double gbsCenitGdo1;
	private double gbsCenitGdo2;
	private double gbsCenitGdo3;
	private double gbsCenitGdo4;
	private double gbsCenitGdo5;
	private double gbsCenitGdo6;
	private double gbsCenitGdo7;
	private double gbsSapGdo1;
	private double gbsSapGdo2;
	private double gbsSapGdo3;
	private double gbsSapGdo4;
	private double gbsSapGdo5;
	private double gbsSapGdo6;
	private double gbsSapGdo7;
	private double gbsOnsiteGdo1;
	private double gbsOnsiteGdo2;
	private double gbsOnsiteGdo3;
	private double gbsOnsiteGdo4;
	private double gbsOnsiteGdo5;
	private double gbsOnsiteGdo6;
	private double gbsOnsiteGdo7;
	private double dir;
	private double itsCenitGdo1;
	private double itsCenitGdo2;
	private double itsCenitGdo3;
	private double itsCenitGdo4;
	private double itsCenitGdo5;
	private double itsCenitGdo6;
	private double itsCenitGdo7;
	private double itsOnsiteGdo1;
	private double itsOnsiteGdo2;
	private double itsOnsiteGdo3;
	private double itsOnsiteGdo4;
	private double itsOnsiteGdo5;
	private double itsOnsiteGdo6;
	private double itsOnsiteGdo7;

	public Itr() {
	}

	public Itr(int idProyecto, double gbsCenitGdo1, double gbsCenitGdo2, double gbsCenitGdo3, double gbsCenitGdo4,
			double gbsCenitGdo5, double gbsCenitGdo6, double gbsCenitGdo7, double gbsSapGdo1, double gbsSapGdo2,
			double gbsSapGdo3, double gbsSapGdo4, double gbsSapGdo5, double gbsSapGdo6, double gbsSapGdo7,
			double gbsOnsiteGdo1, double gbsOnsiteGdo2, double gbsOnsiteGdo3, double gbsOnsiteGdo4,
			double gbsOnsiteGdo5, double gbsOnsiteGdo6, double gbsOnsiteGdo7, double dir, double itsCenitGdo1,
			double itsCenitGdo2, double itsCenitGdo3, double itsCenitGdo4, double itsCenitGdo5, double itsCenitGdo6,
			double itsCenitGdo7, double itsOnsiteGdo1, double itsOnsiteGdo2, double itsOnsiteGdo3, double itsOnsiteGdo4,
			double itsOnsiteGdo5, double itsOnsiteGdo6, double itsOnsiteGdo7) {
		this.idProyecto = idProyecto;
		this.gbsCenitGdo1 = gbsCenitGdo1;
		this.gbsCenitGdo2 = gbsCenitGdo2;
		this.gbsCenitGdo3 = gbsCenitGdo3;
		this.gbsCenitGdo4 = gbsCenitGdo4;
		this.gbsCenitGdo5 = gbsCenitGdo5;
		this.gbsCenitGdo6 = gbsCenitGdo6;
		this.gbsCenitGdo7 = gbsCenitGdo7;
		this.gbsSapGdo1 = gbsSapGdo1;
		this.gbsSapGdo2 = gbsSapGdo2;
		this.gbsSapGdo3 = gbsSapGdo3;
		this.gbsSapGdo4 = gbsSapGdo4;
		this.gbsSapGdo5 = gbsSapGdo5;
		this.gbsSapGdo6 = gbsSapGdo6;
		this.gbsSapGdo7 = gbsSapGdo7;
		this.gbsOnsiteGdo1 = gbsOnsiteGdo1;
		this.gbsOnsiteGdo2 = gbsOnsiteGdo2;
		this.gbsOnsiteGdo3 = gbsOnsiteGdo3;
		this.gbsOnsiteGdo4 = gbsOnsiteGdo4;
		this.gbsOnsiteGdo5 = gbsOnsiteGdo5;
		this.gbsOnsiteGdo6 = gbsOnsiteGdo6;
		this.gbsOnsiteGdo7 = gbsOnsiteGdo7;
		this.dir = dir;
		this.itsCenitGdo1 = itsCenitGdo1;
		this.itsCenitGdo2 = itsCenitGdo2;
		this.itsCenitGdo3 = itsCenitGdo3;
		this.itsCenitGdo4 = itsCenitGdo4;
		this.itsCenitGdo5 = itsCenitGdo5;
		this.itsCenitGdo6 = itsCenitGdo6;
		this.itsCenitGdo7 = itsCenitGdo7;
		this.itsOnsiteGdo1 = itsOnsiteGdo1;
		this.itsOnsiteGdo2 = itsOnsiteGdo2;
		this.itsOnsiteGdo3 = itsOnsiteGdo3;
		this.itsOnsiteGdo4 = itsOnsiteGdo4;
		this.itsOnsiteGdo5 = itsOnsiteGdo5;
		this.itsOnsiteGdo6 = itsOnsiteGdo6;
		this.itsOnsiteGdo7 = itsOnsiteGdo7;
	}

	@Id

	@Column(name = "idProyecto", unique = true, nullable = false)
	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	@Column(name = "GBS_CENIT_GDO1", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo1() {
		return this.gbsCenitGdo1;
	}

	public void setGbsCenitGdo1(double gbsCenitGdo1) {
		this.gbsCenitGdo1 = gbsCenitGdo1;
	}

	@Column(name = "GBS_CENIT_GDO2", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo2() {
		return this.gbsCenitGdo2;
	}

	public void setGbsCenitGdo2(double gbsCenitGdo2) {
		this.gbsCenitGdo2 = gbsCenitGdo2;
	}

	@Column(name = "GBS_CENIT_GDO3", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo3() {
		return this.gbsCenitGdo3;
	}

	public void setGbsCenitGdo3(double gbsCenitGdo3) {
		this.gbsCenitGdo3 = gbsCenitGdo3;
	}

	@Column(name = "GBS_CENIT_GDO4", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo4() {
		return this.gbsCenitGdo4;
	}

	public void setGbsCenitGdo4(double gbsCenitGdo4) {
		this.gbsCenitGdo4 = gbsCenitGdo4;
	}

	@Column(name = "GBS_CENIT_GDO5", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo5() {
		return this.gbsCenitGdo5;
	}

	public void setGbsCenitGdo5(double gbsCenitGdo5) {
		this.gbsCenitGdo5 = gbsCenitGdo5;
	}

	@Column(name = "GBS_CENIT_GDO6", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo6() {
		return this.gbsCenitGdo6;
	}

	public void setGbsCenitGdo6(double gbsCenitGdo6) {
		this.gbsCenitGdo6 = gbsCenitGdo6;
	}

	@Column(name = "GBS_CENIT_GDO7", nullable = false, precision = 22, scale = 0)
	public double getGbsCenitGdo7() {
		return this.gbsCenitGdo7;
	}

	public void setGbsCenitGdo7(double gbsCenitGdo7) {
		this.gbsCenitGdo7 = gbsCenitGdo7;
	}

	@Column(name = "GBS_SAP_GDO1", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo1() {
		return this.gbsSapGdo1;
	}

	public void setGbsSapGdo1(double gbsSapGdo1) {
		this.gbsSapGdo1 = gbsSapGdo1;
	}

	@Column(name = "GBS_SAP_GDO2", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo2() {
		return this.gbsSapGdo2;
	}

	public void setGbsSapGdo2(double gbsSapGdo2) {
		this.gbsSapGdo2 = gbsSapGdo2;
	}

	@Column(name = "GBS_SAP_GDO3", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo3() {
		return this.gbsSapGdo3;
	}

	public void setGbsSapGdo3(double gbsSapGdo3) {
		this.gbsSapGdo3 = gbsSapGdo3;
	}

	@Column(name = "GBS_SAP_GDO4", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo4() {
		return this.gbsSapGdo4;
	}

	public void setGbsSapGdo4(double gbsSapGdo4) {
		this.gbsSapGdo4 = gbsSapGdo4;
	}

	@Column(name = "GBS_SAP_GDO5", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo5() {
		return this.gbsSapGdo5;
	}

	public void setGbsSapGdo5(double gbsSapGdo5) {
		this.gbsSapGdo5 = gbsSapGdo5;
	}

	@Column(name = "GBS_SAP_GDO6", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo6() {
		return this.gbsSapGdo6;
	}

	public void setGbsSapGdo6(double gbsSapGdo6) {
		this.gbsSapGdo6 = gbsSapGdo6;
	}

	@Column(name = "GBS_SAP_GDO7", nullable = false, precision = 22, scale = 0)
	public double getGbsSapGdo7() {
		return this.gbsSapGdo7;
	}

	public void setGbsSapGdo7(double gbsSapGdo7) {
		this.gbsSapGdo7 = gbsSapGdo7;
	}

	@Column(name = "GBS_ONSITE_GDO1", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo1() {
		return this.gbsOnsiteGdo1;
	}

	public void setGbsOnsiteGdo1(double gbsOnsiteGdo1) {
		this.gbsOnsiteGdo1 = gbsOnsiteGdo1;
	}

	@Column(name = "GBS_ONSITE_GDO2", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo2() {
		return this.gbsOnsiteGdo2;
	}

	public void setGbsOnsiteGdo2(double gbsOnsiteGdo2) {
		this.gbsOnsiteGdo2 = gbsOnsiteGdo2;
	}

	@Column(name = "GBS_ONSITE_GDO3", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo3() {
		return this.gbsOnsiteGdo3;
	}

	public void setGbsOnsiteGdo3(double gbsOnsiteGdo3) {
		this.gbsOnsiteGdo3 = gbsOnsiteGdo3;
	}

	@Column(name = "GBS_ONSITE_GDO4", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo4() {
		return this.gbsOnsiteGdo4;
	}

	public void setGbsOnsiteGdo4(double gbsOnsiteGdo4) {
		this.gbsOnsiteGdo4 = gbsOnsiteGdo4;
	}

	@Column(name = "GBS_ONSITE_GDO5", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo5() {
		return this.gbsOnsiteGdo5;
	}

	public void setGbsOnsiteGdo5(double gbsOnsiteGdo5) {
		this.gbsOnsiteGdo5 = gbsOnsiteGdo5;
	}

	@Column(name = "GBS_ONSITE_GDO6", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo6() {
		return this.gbsOnsiteGdo6;
	}

	public void setGbsOnsiteGdo6(double gbsOnsiteGdo6) {
		this.gbsOnsiteGdo6 = gbsOnsiteGdo6;
	}

	@Column(name = "GBS_ONSITE_GDO7", nullable = false, precision = 22, scale = 0)
	public double getGbsOnsiteGdo7() {
		return this.gbsOnsiteGdo7;
	}

	public void setGbsOnsiteGdo7(double gbsOnsiteGdo7) {
		this.gbsOnsiteGdo7 = gbsOnsiteGdo7;
	}

	@Column(name = "DIR", nullable = false, precision = 22, scale = 0)
	public double getDir() {
		return this.dir;
	}

	public void setDir(double dir) {
		this.dir = dir;
	}

	@Column(name = "ITS_CENIT_GDO1", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo1() {
		return this.itsCenitGdo1;
	}

	public void setItsCenitGdo1(double itsCenitGdo1) {
		this.itsCenitGdo1 = itsCenitGdo1;
	}

	@Column(name = "ITS_CENIT_GDO2", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo2() {
		return this.itsCenitGdo2;
	}

	public void setItsCenitGdo2(double itsCenitGdo2) {
		this.itsCenitGdo2 = itsCenitGdo2;
	}

	@Column(name = "ITS_CENIT_GDO3", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo3() {
		return this.itsCenitGdo3;
	}

	public void setItsCenitGdo3(double itsCenitGdo3) {
		this.itsCenitGdo3 = itsCenitGdo3;
	}

	@Column(name = "ITS_CENIT_GDO4", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo4() {
		return this.itsCenitGdo4;
	}

	public void setItsCenitGdo4(double itsCenitGdo4) {
		this.itsCenitGdo4 = itsCenitGdo4;
	}

	@Column(name = "ITS_CENIT_GDO5", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo5() {
		return this.itsCenitGdo5;
	}

	public void setItsCenitGdo5(double itsCenitGdo5) {
		this.itsCenitGdo5 = itsCenitGdo5;
	}

	@Column(name = "ITS_CENIT_GDO6", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo6() {
		return this.itsCenitGdo6;
	}

	public void setItsCenitGdo6(double itsCenitGdo6) {
		this.itsCenitGdo6 = itsCenitGdo6;
	}

	@Column(name = "ITS_CENIT_GDO7", nullable = false, precision = 22, scale = 0)
	public double getItsCenitGdo7() {
		return this.itsCenitGdo7;
	}

	public void setItsCenitGdo7(double itsCenitGdo7) {
		this.itsCenitGdo7 = itsCenitGdo7;
	}

	@Column(name = "ITS_ONSITE_GDO1", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo1() {
		return this.itsOnsiteGdo1;
	}

	public void setItsOnsiteGdo1(double itsOnsiteGdo1) {
		this.itsOnsiteGdo1 = itsOnsiteGdo1;
	}

	@Column(name = "ITS_ONSITE_GDO2", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo2() {
		return this.itsOnsiteGdo2;
	}

	public void setItsOnsiteGdo2(double itsOnsiteGdo2) {
		this.itsOnsiteGdo2 = itsOnsiteGdo2;
	}

	@Column(name = "ITS_ONSITE_GDO3", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo3() {
		return this.itsOnsiteGdo3;
	}

	public void setItsOnsiteGdo3(double itsOnsiteGdo3) {
		this.itsOnsiteGdo3 = itsOnsiteGdo3;
	}

	@Column(name = "ITS_ONSITE_GDO4", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo4() {
		return this.itsOnsiteGdo4;
	}

	public void setItsOnsiteGdo4(double itsOnsiteGdo4) {
		this.itsOnsiteGdo4 = itsOnsiteGdo4;
	}

	@Column(name = "ITS_ONSITE_GDO5", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo5() {
		return this.itsOnsiteGdo5;
	}

	public void setItsOnsiteGdo5(double itsOnsiteGdo5) {
		this.itsOnsiteGdo5 = itsOnsiteGdo5;
	}

	@Column(name = "ITS_ONSITE_GDO6", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo6() {
		return this.itsOnsiteGdo6;
	}

	public void setItsOnsiteGdo6(double itsOnsiteGdo6) {
		this.itsOnsiteGdo6 = itsOnsiteGdo6;
	}

	@Column(name = "ITS_ONSITE_GDO7", nullable = false, precision = 22, scale = 0)
	public double getItsOnsiteGdo7() {
		return this.itsOnsiteGdo7;
	}

	public void setItsOnsiteGdo7(double itsOnsiteGdo7) {
		this.itsOnsiteGdo7 = itsOnsiteGdo7;
	}

}
