package com.becarios.proyecto_definitivo.model.horas_costes;
// Generated 19-abr-2017 17:37:47 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "delivery", catalog = "HE")
public class Delivery implements java.io.Serializable {

	private DeliveryId id;
	private int porcentaje;
	private boolean internaPractica;
	private int horas;
	private int coste;

	public Delivery() {
	}

	public Delivery(DeliveryId id, int porcentaje, boolean internaPractica, int horas, int coste) {
		this.id = id;
		this.porcentaje = porcentaje;
		this.internaPractica = internaPractica;
		this.horas = horas;
		this.coste = coste;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProyecto", column = @Column(name = "idProyecto", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "Nombre", nullable = false, length = 45)) })
	public DeliveryId getId() {
		return this.id;
	}

	public void setId(DeliveryId id) {
		this.id = id;
	}

	@Column(name = "Porcentaje", nullable = false)
	public int getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(int porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "internaPractica", nullable = false)
	public boolean isInternaPractica() {
		return this.internaPractica;
	}

	public void setInternaPractica(boolean internaPractica) {
		this.internaPractica = internaPractica;
	}

	@Column(name = "Horas", nullable = false)
	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	@Column(name = "Coste", nullable = false)
	public int getCoste() {
		return this.coste;
	}

	public void setCoste(int coste) {
		this.coste = coste;
	}

}
