package com.becarios.proyecto_definitivo.model.horas_costes;
// Generated 28-feb-2017 16:10:32 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gestionexterno generated by hbm2java
 */
@Entity
@Table(name = "gestionexterno", catalog = "HE")
public class Gestionexterno implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int porcentaje;
	private int horas;
	private int coste;

	public Gestionexterno() {
	}

	public Gestionexterno(String nombre, int porcentaje, int horas, int coste) {
		this.nombre = nombre;
		this.porcentaje = porcentaje;
		this.horas = horas;
		this.coste = coste;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Porcentaje", nullable = false)
	public int getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(int porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "Horas", nullable = false)
	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	@Column(name = "Coste", nullable = false)
	public int getCoste() {
		return this.coste;
	}

	public void setCoste(int coste) {
		this.coste = coste;
	}

}
