
package com.becarios.proyecto_definitivo.model.horas_costes;
// Generated 28-feb-2017 16:10:32 by Hibernate Tools 5.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Riesgo generated by hbm2java
 */
@Entity
@Table(name = "riesgo", catalog = "HE")
public class Riesgo implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private int num;

    public Riesgo() {
    }

    public Riesgo(String nombre, int num) {
        this.nombre = nombre;
        this.num = num;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "Num", nullable = false)
    public int getNum() {
        return this.num;
    }

    public void setNum(int num) {
        this.num = num;
    }

}
