package com.becarios.proyecto_definitivo.model.horas_costes;
// Generated 22-mar-2017 16:09:41 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Valoracionfinal generated by hbm2java
 */
@Entity
@Table(name = "valoracionfinal", catalog = "HE")
public class Valoracionfinal implements java.io.Serializable {

	private int idProyecto;
	private String nombre;
	private int horas;
	private int coste;

	public Valoracionfinal() {
	}

	public Valoracionfinal(int idProyecto, String nombre, int horas, int coste) {
		this.idProyecto = idProyecto;
		this.nombre = nombre;
		this.horas = horas;
		this.coste = coste;
	}

	@Id

	@Column(name = "idProyecto", nullable = false)
	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	@Id
	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Horas", nullable = false)
	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	@Column(name = "Coste", nullable = false)
	public int getCoste() {
		return this.coste;
	}

	public void setCoste(int coste) {
		this.coste = coste;
	}

}
