package com.becarios.proyecto_definitivo.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto", catalog = "HE", schema = "USUARI")
public class Proyecto implements java.io.Serializable {

    private Integer id;
    private String descripcion;
    private String codigoProyecto;
    private String nombre;
    private boolean editado;

    public Proyecto() {
    }

    public Proyecto(String codigoProyecto, String nombre, boolean editado) {
        this.codigoProyecto = codigoProyecto;
        this.nombre = nombre;
        this.editado = editado;
    }

    public Proyecto(String descripcion, String codigoProyecto, String nombre, boolean editado) {
        this.descripcion = descripcion;
        this.codigoProyecto = codigoProyecto;
        this.nombre = nombre;
        this.editado = editado;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "CodigoProyecto", nullable = false, length = 45)
    public String getCodigoProyecto() {
        return this.codigoProyecto;
    }

    public void setCodigoProyecto(String codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }

    @Column(name = "Nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "IsEditado", nullable = false)
    public boolean isEditado() {
        return editado;
    }

    public void setEditado(boolean editado) {
        this.editado = editado;
    }

    @Column(name = "DESCRIPCION", length = 200)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
