package com.becarios.proyecto_definitivo.model.criterios;
// Generated 23-mar-2017 16:52:30 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CasosDeUso generated by hbm2java
 */
@Entity
@Table(name = "casos_de_uso", catalog = "HE", uniqueConstraints = @UniqueConstraint(columnNames = "IdProyecto"))
public class CasosDeUso implements java.io.Serializable {

	private CasosDeUsoId id;
	private String codigo;
	private double totalFila;
	private String nombre;
	private String modulo;

	public CasosDeUso() {
	}

	public CasosDeUso(CasosDeUsoId id, String codigo, double totalFila, String nombre, String modulo) {
		this.id = id;
		this.codigo = codigo;
		this.totalFila = totalFila;
		this.nombre = nombre;
		this.modulo = modulo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "idProyecto", column = @Column(name = "IdProyecto", unique = true, nullable = false)) })
	public CasosDeUsoId getId() {
		return this.id;
	}

	public void setId(CasosDeUsoId id) {
		this.id = id;
	}

	@Column(name = "Codigo", nullable = false, length = 45)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "TotalFila", nullable = false, precision = 22, scale = 0)
	public double getTotalFila() {
		return this.totalFila;
	}

	public void setTotalFila(double totalFila) {
		this.totalFila = totalFila;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Modulo", nullable = false, length = 45)
	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

}
