package com.becarios.proyecto_definitivo.model.criterios;
// Generated 20-mar-2017 16:23:01 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cuoriginal generated by hbm2java
 */
@Entity
@Table(name = "cuoriginal", catalog = "HE")
public class Cuoriginal extends Tabla implements java.io.Serializable {

	private int casosdeUsosCodigo;
	private String complejidad;
	private int total;

	public Cuoriginal() {
	}

	public Cuoriginal(int casosdeUsosCodigo, String complejidad, int total) {
		this.casosdeUsosCodigo = casosdeUsosCodigo;
		this.complejidad = complejidad;
		this.total = total;
	}

	@Id

	@Column(name = "CasosdeUsos_Codigo", unique = true, nullable = false)
	public int getCasosdeUsosCodigo() {
		return this.casosdeUsosCodigo;
	}

	public void setCasosdeUsosCodigo(int casosdeUsosCodigo) {
		this.casosdeUsosCodigo = casosdeUsosCodigo;
	}

	@Column(name = "Complejidad", nullable = false, length = 45)
	public String getComplejidad() {
		return this.complejidad;
	}

	public void setComplejidad(String complejidad) {
		this.complejidad = complejidad;
	}

	@Column(name = "Total", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
