package com.becarios.proyecto_definitivo.model.criterios;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.becarios.proyecto_definitivo.model.criterios.CUOriginal;
import com.becarios.proyecto_definitivo.model.criterios.Integracion;
import com.becarios.proyecto_definitivo.model.criterios.Negocio;
import com.becarios.proyecto_definitivo.model.criterios.Perfiles;
import com.becarios.proyecto_definitivo.model.criterios.Persistencia;
import com.becarios.proyecto_definitivo.model.criterios.Vista;

@Entity
@Table(name = "CASOS_DE_USO", schema = "USUARI")
public class Modulo implements Serializable {

    private static final long serialVersionUID = 981077378061096685L;

    private String codigoProyecto = "0";
    private String codigo;
    private String nombre;
    private String casoDeUso;
    private int total;

    List<Tabla> tablas = new ArrayList<Tabla>();

    public Modulo(String codigoProyecto, String code, List<Tabla> tablas) {
        this.codigoProyecto = codigoProyecto;
        this.codigo = code;
        this.tablas = tablas;
        nombre = "nombreprueba";
        casoDeUso = "Caso de uso";
        total = 0;

    }

    public Modulo(String codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
        this.codigo = ""; // Autogenerated Value
        this.casoDeUso = "Caso de Uso";
        this.nombre = "Nombre";
        total = 0;
        this.setDefaultTablas();
    }

    @Column(name = "Nombre", length = 40)
    public String getName() {
        return nombre;
    }

    public void setName(String name) {
        this.nombre = name;
    }

    @Id
    @Column(name = "Codigo", unique = true, nullable = false, length = 8)
    public String getCode() {
        return codigo;
    }

    public void setCode(String code) {
        this.codigo = code;
    }

    @Column(name = "Modulo", length = 40)
    public String getCaseOfUse() {
        return casoDeUso;
    }

    public void setCaseOfUse(String caseOfUse) {
        this.casoDeUso = caseOfUse;
    }

    @Column(name = "TotalFila", precision = 0, scale = 0)
    public int getTotal() {
        return total;
    }

    public void setTotal(float total) {
        this.total = (int) total;
    }

    public List<Tabla> loadTablas() {
        return tablas;
    }

    public void setTablas(List<Tabla> tablas) {
        this.tablas = tablas;
    }

    public void setDefaultTablas() {
        tablas.add(0, new Perfiles(this.codigo));
        tablas.add(1, new Vista(this.codigo));
        tablas.add(2, new Negocio(this.codigo));
        tablas.add(3, new Persistencia(this.codigo));
        tablas.add(4, new CUOriginal(this.codigo));
        tablas.add(5, new Integracion(this.codigo));

    }

    public void apply(String code, String name, String caseOfUse) {
        this.codigo = code;
        this.casoDeUso = caseOfUse;
        this.nombre = name;

    }

    @Id
    @Column(name = "Proyecto_IdProyecto", length = 8)
    public String getCodigoProyecto() {
        return codigoProyecto;
    }

    public void setCodigoProyecto(String codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }

}
