package com.becarios.proyecto_definitivo.model.criterios;
// Generated 20-mar-2017 16:18:07 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persistencia generated by hbm2java
 */
@Entity
@Table(name = "persistencia", catalog = "HE")
public class Persistencia extends Tabla implements java.io.Serializable {

	private int casosdeUsosCodigo;
	private int nro;
	private String accesos;
	private int total;

	public Persistencia() {
	}

	public Persistencia(int casosdeUsosCodigo, int nro, String accesos, int total) {
		this.casosdeUsosCodigo = casosdeUsosCodigo;
		this.nro = nro;
		this.accesos = accesos;
		this.total = total;
	}

	@Id

	@Column(name = "CasosdeUsos_Codigo", unique = true, nullable = false)
	public int getCasosdeUsosCodigo() {
		return this.casosdeUsosCodigo;
	}

	public void setCasosdeUsosCodigo(int casosdeUsosCodigo) {
		this.casosdeUsosCodigo = casosdeUsosCodigo;
	}

	@Column(name = "Nro", nullable = false)
	public int getNro() {
		return this.nro;
	}

	public void setNro(int nro) {
		this.nro = nro;
	}

	@Column(name = "Accesos", nullable = false, length = 45)
	public String getAccesos() {
		return this.accesos;
	}

	public void setAccesos(String accesos) {
		this.accesos = accesos;
	}

	@Column(name = "Total", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
