package com.becarios.proyecto_definitivo.model.criterios;
// Generated 20-mar-2017 16:18:07 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vista generated by hbm2java
 */
@Entity
@Table(name = "vista", catalog = "HE")
public class Vista extends Tabla implements java.io.Serializable {

	private int casosdeUsosCodigo;
	private int nro;
	private String complejidad;
	private int total;
	private String campos;
	private String listados;
	private String botones;

	public Vista() {
	}

	public Vista(int casosdeUsosCodigo, int nro, String complejidad, int total, String campos, String listados,
			String botones) {
		this.casosdeUsosCodigo = casosdeUsosCodigo;
		this.nro = nro;
		this.complejidad = complejidad;
		this.total = total;
		this.campos = campos;
		this.listados = listados;
		this.botones = botones;
	}

	@Id

	@Column(name = "CasosdeUsos_Codigo", unique = true, nullable = false)
	public int getCasosdeUsosCodigo() {
		return this.casosdeUsosCodigo;
	}

	public void setCasosdeUsosCodigo(int casosdeUsosCodigo) {
		this.casosdeUsosCodigo = casosdeUsosCodigo;
	}

	@Column(name = "Nro", nullable = false)
	public int getNro() {
		return this.nro;
	}

	public void setNro(int nro) {
		this.nro = nro;
	}

	@Column(name = "Complejidad", nullable = false, length = 45)
	public String getComplejidad() {
		return this.complejidad;
	}

	public void setComplejidad(String complejidad) {
		this.complejidad = complejidad;
	}

	@Column(name = "Total", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	@Column(name = "Campos", nullable = false, length = 45)
	public String getCampos() {
		return this.campos;
	}

	public void setCampos(String campos) {
		this.campos = campos;
	}

	@Column(name = "Listados", nullable = false, length = 45)
	public String getListados() {
		return this.listados;
	}

	public void setListados(String listados) {
		this.listados = listados;
	}

	@Column(name = "Botones", nullable = false, length = 45)
	public String getBotones() {
		return this.botones;
	}

	public void setBotones(String botones) {
		this.botones = botones;
	}

}
