package com.becarios.proyecto_definitivo.dto;
// Generated 22-mar-2017 16:09:41 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto", catalog = "HE")
public class ProyectoDto implements java.io.Serializable {

    private Integer id;
    private String descripcion;
    private String codigoProyecto;
    private String nombre;
    private boolean editado;

    public ProyectoDto() {
    }

    public ProyectoDto(String codigoProyecto, String nombre, boolean editado) {
        this.codigoProyecto = codigoProyecto;
        this.nombre = nombre;
        this.editado = editado;
    }

    public ProyectoDto(String descripcion, String codigoProyecto, String nombre, boolean editado) {
        this.descripcion = descripcion;
        this.codigoProyecto = codigoProyecto;
        this.nombre = nombre;
        this.editado = editado;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getCodigoProyecto() {
        return this.codigoProyecto;
    }

    public void setCodigoProyecto(String codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean isEditado() {
        return this.editado;
    }

    public void setEditado(boolean editado) {
        this.editado = editado;
    }

}
