package com.becarios.proyecto_definitivo.service.criterios;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.becarios.proyecto_definitivo.dao.criterios.ModuleDao;
import com.becarios.proyecto_definitivo.model.criterios.CUOriginal;
import com.becarios.proyecto_definitivo.model.criterios.Integracion;
import com.becarios.proyecto_definitivo.model.criterios.Modulo;
import com.becarios.proyecto_definitivo.model.criterios.Negocio;
import com.becarios.proyecto_definitivo.model.criterios.Perfiles;
import com.becarios.proyecto_definitivo.model.criterios.Persistencia;
import com.becarios.proyecto_definitivo.model.criterios.Vista;

@Service("ModuleService")
@Transactional
public class ModuleServiceImpl implements ModuleService {

    @Autowired
    private ModuleDao dao;

    @Override
    public Modulo findByCode(int id) {
        return dao.findByCode(id);
    }

    @Override
    public void saveModulo(Modulo modulo) {
        dao.saveModule(modulo);

    }

    @Override
    public void updateModulo(Modulo modulo) {
        Modulo entity = dao.findByCode(modulo.getId());
        if (entity != null) {
            entity.setNombre(modulo.getNombre());
            entity.setModulo(modulo.getModulo());
            entity.setTotalFila(modulo.getTotalFila());
        }

    }

    @Override
    public void deleteModuloByCode(int id) {
        dao.deleteModuleByCode(id);

    }

    @Override
    public List<Modulo> findAllModulo(int id) {
        return dao.findAllModules(id);
    }

    @Override
    public void createModulo(int id) {

        Modulo m = new Modulo();

        m.setNombre("Nombre por defecto");
        m.setCodigo("Codigo"); // Autogenerated Value
        m.setModulo("Caso de uso" + " por defecto");
        m.setTotalFila(5);
        m.setIdProyecto(id);

    }

    @Override
    public boolean AddModulo(int idProyecto, int id, String code, String caseOfUse, String name, int perfilesTotal,
            int perfilesNro, int perfilesComplejidad, int vistaTotal, int vistaNro, int vistaCampos,
            int vistaComplejidad, int vistaListados, int vistaBotones, int negocioTotal, int negocioNro,
            int negocioLogica, int persistenciaTotal, int persistenciaNro, int persistenciaAccesos, int cuTotal,
            int cuDificultad, int integracionTotal, int integracionNro, int integracionComplejidad) {
        try {
            // Crear el Objeto a Guardar
            Modulo modulo = new Modulo();
            modulo.setId(id);
            modulo.setModulo(caseOfUse);
            modulo.setNombre(name);

            // Llamar al service para que lo guarde

            // Crea objeto Perfiles
            Perfiles perfiles = new Perfiles(code);
            perfiles.setCodigoRef(code);
            perfiles.setNro(perfilesNro);
            perfiles.setComplejidad(perfilesComplejidad);
            perfiles.setTotal(perfilesTotal);

            // Crea objeto Vista
            Vista vista = new Vista(code);
            vista.setCodigoRef(code);
            vista.setNro(vistaNro);
            vista.setBotones(vistaBotones);
            vista.setCampos(vistaCampos);
            vista.setComplejidad(vistaComplejidad);
            vista.setListados(vistaListados);
            vista.setTotal(vistaTotal);

            // Crea objeto Negocio
            Negocio negocio = new Negocio(code);
            negocio.setCodigoRef(code);
            negocio.setNro(negocioNro);
            negocio.setLogica(negocioLogica);
            negocio.setTotal(negocioTotal);

            // Crea objeto Persistencia
            Persistencia persistencia = new Persistencia(code);
            persistencia.setCodigoRef(code);
            persistencia.setNro(persistenciaNro);
            persistencia.setAccesos(persistenciaAccesos);
            persistencia.setTotal(persistenciaTotal);

            // Crea objeto CUOriginal
            CUOriginal cu = new CUOriginal(code);
            cu.setCodigoRef(code);
            cu.setDificultad(cuDificultad);
            cu.setTotal(cuTotal);

            // Crea objeto Integracion
            Integracion integracion = new Integracion(code);
            integracion.setCodigoRef(code);
            integracion.setNro(integracionNro);
            integracion.setComplejidad(integracionComplejidad);
            integracion.setTotal(integracionTotal);

            float total;
            // lo calcula el procedure de la base de datos.
            // if (editado){
            if (!true) {
                total = (float) ((perfilesTotal + vistaTotal + negocioTotal + persistenciaTotal) / 7);
            } else {
                total = (float) ((perfilesTotal + vistaTotal + negocioTotal + persistenciaTotal) * 0.8 / 7
                        + integracionTotal * 0.2);
            }

            modulo.setTotalFila(total);

            this.saveModulo(modulo);
            // Not implemented yet
            // dao.saveTablas(perfiles,vista,negocio,persistencia,cu,integracion)

        } catch (Exception e) {
            return false;
        }
        return true;
    }

}
