package com.becarios.proyecto_definitivo.service.criterios;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.becarios.proyecto_definitivo.dao.criterios.ModuleDao;
import com.becarios.proyecto_definitivo.model.criterios.CasosDeUso;
import com.becarios.proyecto_definitivo.model.criterios.CasosDeUsoId;
import com.becarios.proyecto_definitivo.model.criterios.Cuoriginal;
import com.becarios.proyecto_definitivo.model.criterios.Integracion;
import com.becarios.proyecto_definitivo.model.criterios.Negocio;
import com.becarios.proyecto_definitivo.model.criterios.Perfiles;
import com.becarios.proyecto_definitivo.model.criterios.Persistencia;
import com.becarios.proyecto_definitivo.model.criterios.Vista;

@Service("ModuleService")
@Transactional
public class ModuleServiceImpl implements ModuleService {

    @Autowired
    private ModuleDao dao;

    @Override
    public CasosDeUso findByCode(int id) {
        return dao.findByCode(id);
    }

    @Override
    public void saveModulo(CasosDeUso modulo) {
        dao.saveModule(modulo);

    }

    @Override
    public void updateModulo(CasosDeUso modulo) {
        CasosDeUso entity = dao.findByCode(modulo.getId().getId());
        if (entity != null) {
            entity.setNombre(modulo.getNombre());
            entity.setModulo(modulo.getModulo());
            entity.setTotalFila(modulo.getTotalFila());
        }

    }

    @Override
    public void deleteModuloByCode(int id) {
        dao.deleteModuleByCode(id);

    }

    @Override
    public List<CasosDeUso> findAllModulo(int id) {
        return dao.findAllModules(id);
    }

    @Override
    public void createModulo(int id) {

        CasosDeUso m = new CasosDeUso();

        m.setNombre("Nombre por defecto");
        m.setCodigo("Codigo"); // Autogenerated Value
        m.setModulo("Caso de uso" + " por defecto");
        m.setTotalFila(5);
        CasosDeUsoId c = new CasosDeUsoId();
        c.setIdProyecto(id);
        m.setId(c);

    }

    @Override
    public boolean AddModulo(int idProyecto, int id, String code, String caseOfUse, String name, int perfilesTotal,
            int perfilesNro, int perfilesComplejidad, int vistaTotal, int vistaNro, int vistaCampos,
            int vistaComplejidad, int vistaListados, int vistaBotones, int negocioTotal, int negocioNro,
            int negocioLogica, int persistenciaTotal, int persistenciaNro, int persistenciaAccesos, int cuTotal,
            int cuDificultad, int integracionTotal, int integracionNro, int integracionComplejidad) {
        try {
            // Crear el Objeto a Guardar
            CasosDeUso modulo = new CasosDeUso();
            modulo.setCodigo(code);
            modulo.setModulo(caseOfUse);
            modulo.setNombre(name);

            // Llamar al service para que lo guarde

            // Crea objeto Perfiles
            Perfiles perfiles = new Perfiles();
            perfiles.setCasosdeUsosCodigo(id);
            perfiles.setNro(perfilesNro);
            perfiles.setComplejidad(perfilesComplejidad);
            perfiles.setTotal(perfilesTotal);

            // Crea objeto Vista
            Vista vista = new Vista();
            vista.setCasosdeUsosCodigo(id);
            vista.setNro(vistaNro);
            vista.setBotones(vistaBotones);
            vista.setCampos(vistaCampos);
            vista.setComplejidad(vistaComplejidad);
            vista.setListados(vistaListados);
            vista.setTotal(vistaTotal);

            // Crea objeto Negocio
            Negocio negocio = new Negocio();
            negocio.setCasosdeUsosCodigo(id);
            negocio.setNro(negocioNro);
            negocio.setLogica(negocioLogica);
            negocio.setTotal(negocioTotal);

            // Crea objeto Persistencia
            Persistencia persistencia = new Persistencia();
            persistencia.setCasosdeUsosCodigo(id);
            persistencia.setNro(persistenciaNro);
            persistencia.setAccesos(persistenciaAccesos);
            persistencia.setTotal(persistenciaTotal);

            // Crea objeto CUOriginal
            Cuoriginal cu = new Cuoriginal();
            cu.setCasosdeUsosCodigo(id);
            cu.setComplejidad(cuDificultad);
            cu.setTotal(cuTotal);

            // Crea objeto Integracion
            Integracion integracion = new Integracion();
            integracion.setCasosdeUsosCodigo(id);
            integracion.setNro(integracionNro);
            integracion.setComplejidad(integracionComplejidad);
            integracion.setTotal(integracionTotal);

            float total;
            // lo calcula el procedure de la base de datos.
            // if (editado){
            if (!true) {
                total = (float) ((perfilesTotal + vistaTotal + negocioTotal + persistenciaTotal) / 7);
            } else {
                total = (float) ((perfilesTotal + vistaTotal + negocioTotal + persistenciaTotal) * 0.8 / 7
                        + integracionTotal * 0.2);
            }

            modulo.setTotalFila(total);

            this.saveModulo(modulo);
            // Not implemented yet
            dao.saveModule(modulo);
            // dao.saveTablas(perfiles, vista, negocio, persistencia, cu,
            // integracion);

        } catch (Exception e) {
            return false;
        }
        return true;
    }

}
