package com.becarios.proyecto_definitivo.model.condicionantes;
// Generated 22-mar-2017 16:50:19 by Hibernate Tools 5.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Condicionantes generated by hbm2java
 */
@Entity
@Table(name = "condicionantes", catalog = "HE")
public class Condicionantes implements java.io.Serializable {

	private CondicionantesId id;
	private String descripcion;
	private boolean estimacion;
	private int idProyecto;

	public Condicionantes(CondicionantesId condicionanteid) {
		this.id=condicionanteid;
	}
	
	public Condicionantes(){
		
	}

	public Condicionantes(CondicionantesId id, String descripcion, boolean estimacion, int idProyecto) {
		this.id = id;
		this.descripcion = descripcion;
		this.estimacion = estimacion;
		this.idProyecto=idProyecto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public CondicionantesId getId() {
		return this.id;
	}

	public void setId(CondicionantesId condicionantesid) {
		this.id = condicionantesid;
	}

	
	@Column(name = "IdProyecto", nullable = false, insertable=false, updatable=false)
	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estimacion", nullable = false)
	public boolean isEstimacion() {
		return this.estimacion;
	}

	public void setEstimacion(boolean estimacion) {
		this.estimacion = estimacion;
	}

}
