package com.becarios.proyecto_definitivo.model.condicionantes;
// Generated 22-mar-2017 16:50:19 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Condicionantes generated by hbm2java
 */
@Entity
@Table(name = "condicionantes", catalog = "HE", uniqueConstraints = { @UniqueConstraint(columnNames = "id"),
		@UniqueConstraint(columnNames = "idProyecto") })
public class Condicionantes implements java.io.Serializable {

	private CondicionantesId id;
	private String descripcion;
	private boolean estimacion;

	public Condicionantes() {
	}

	public Condicionantes(CondicionantesId id, String descripcion, boolean estimacion) {
		this.id = id;
		this.descripcion = descripcion;
		this.estimacion = estimacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", unique = true, nullable = false)),
			@AttributeOverride(name = "idProyecto", column = @Column(name = "idProyecto", unique = true, nullable = false)) })
	public CondicionantesId getId() {
		return this.id;
	}

	public void setId(CondicionantesId id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estimacion", nullable = false)
	public boolean isEstimacion() {
		return this.estimacion;
	}

	public void setEstimacion(boolean estimacion) {
		this.estimacion = estimacion;
	}

}
