package com.becarios.proyecto_definitivo.model.condicionantes;
// Generated 22-mar-2017 16:50:19 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CondicionantesId generated by hbm2java
 */
@Embeddable
public class CondicionantesId implements java.io.Serializable {

	private int id;
	private int idProyecto;

	public CondicionantesId() {
	}

	public CondicionantesId(int id, int idProyecto) {
		this.id = id;
		this.idProyecto = idProyecto;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "idProyecto", unique = true, nullable = false)
	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondicionantesId))
			return false;
		CondicionantesId castOther = (CondicionantesId) other;

		return (this.getId() == castOther.getId()) && (this.getIdProyecto() == castOther.getIdProyecto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdProyecto();
		return result;
	}

}
