package com.becarios.proyecto_definitivo.model.factores_ajustes;
// Generated 20-mar-2017 16:23:01 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArquitecturaRefencial generated by hbm2java
 */
@Entity
@Table(name = "arquitectura_refencial", catalog = "HE")
public class ArquitecturaReferencia implements java.io.Serializable {

	private int idProyecto;
	private String nombre;
	private boolean aplica;
	private boolean definido;
	private int gradoConocimento;
	private int impacto;
	private int riesgo;

	public ArquitecturaReferencia() {
	}

	public ArquitecturaReferencia(int idProyecto, String nombre, boolean aplica, boolean definido, int gradoConocimento,
			int impacto, int riesgo) {
		this.idProyecto = idProyecto;
		this.nombre = nombre;
		this.aplica = aplica;
		this.definido = definido;
		this.gradoConocimento = gradoConocimento;
		this.impacto = impacto;
		this.riesgo = riesgo;
	}

	@Id

	@Column(name = "idProyecto", unique = true, nullable = false)
	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Aplica", nullable = false)
	public boolean isAplica() {
		return this.aplica;
	}

	public void setAplica(boolean aplica) {
		this.aplica = aplica;
	}

	@Column(name = "Definido", nullable = false)
	public boolean isDefinido() {
		return this.definido;
	}

	public void setDefinido(boolean definido) {
		this.definido = definido;
	}

	@Column(name = "gradoConocimento", nullable = false)
	public int getGradoConocimento() {
		return this.gradoConocimento;
	}

	public void setGradoConocimento(int gradoConocimento) {
		this.gradoConocimento = gradoConocimento;
	}

	@Column(name = "Impacto", nullable = false)
	public int getImpacto() {
		return this.impacto;
	}

	public void setImpacto(int impacto) {
		this.impacto = impacto;
	}

	@Column(name = "Riesgo", nullable = false)
	public int getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(int riesgo) {
		this.riesgo = riesgo;
	}

}
