package com.becarios.proyecto_definitivo.model.factores_ajustes;
// Generated 19-abr-2017 17:37:47 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FactorComplejidadTecnica generated by hbm2java
 */
@Entity
@Table(name = "factor_complejidad_tecnica", catalog = "HE")
public class FactorComplejidadTecnica implements java.io.Serializable {

	private FactorComplejidadTecnicaId id;
	private boolean aplica;
	private int gradoDefinicion;
	private int gradoExigencia;
	private int impacto;
	private int riesgo;

	public FactorComplejidadTecnica() {
	}

	public FactorComplejidadTecnica(FactorComplejidadTecnicaId id, boolean aplica, int gradoDefinicion,
			int gradoExigencia, int impacto, int riesgo) {
		this.id = id;
		this.aplica = aplica;
		this.gradoDefinicion = gradoDefinicion;
		this.gradoExigencia = gradoExigencia;
		this.impacto = impacto;
		this.riesgo = riesgo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProyecto", column = @Column(name = "idProyecto", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "Nombre", nullable = false, length = 45)) })
	public FactorComplejidadTecnicaId getId() {
		return this.id;
	}

	public void setId(FactorComplejidadTecnicaId id) {
		this.id = id;
	}

	@Column(name = "Aplica", nullable = false)
	public boolean isAplica() {
		return this.aplica;
	}

	public void setAplica(boolean aplica) {
		this.aplica = aplica;
	}

	@Column(name = "gradoDefinicion", nullable = false)
	public int getGradoDefinicion() {
		return this.gradoDefinicion;
	}

	public void setGradoDefinicion(int gradoDefinicion) {
		this.gradoDefinicion = gradoDefinicion;
	}

	@Column(name = "gradoExigencia", nullable = false)
	public int getGradoExigencia() {
		return this.gradoExigencia;
	}

	public void setGradoExigencia(int gradoExigencia) {
		this.gradoExigencia = gradoExigencia;
	}

	@Column(name = "Impacto", nullable = false)
	public int getImpacto() {
		return this.impacto;
	}

	public void setImpacto(int impacto) {
		this.impacto = impacto;
	}

	@Column(name = "Riesgo", nullable = false)
	public int getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(int riesgo) {
		this.riesgo = riesgo;
	}

}
