package com.becarios.proyecto_definitivo.model.factores_ajustes;
// Generated 19-abr-2017 17:37:47 by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FactorComplejidadAmbiental generated by hbm2java
 */
@Entity
@Table(name = "factor_complejidad_ambiental", catalog = "HE")
public class FactorComplejidadAmbiental implements java.io.Serializable {

	private FactorComplejidadAmbientalId id;
	private int valoracion;
	private int factorCalculado;

	public FactorComplejidadAmbiental() {
	}

	public FactorComplejidadAmbiental(FactorComplejidadAmbientalId id, int valoracion, int factorCalculado) {
		this.id = id;
		this.valoracion = valoracion;
		this.factorCalculado = factorCalculado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProyecto", column = @Column(name = "idProyecto", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "Nombre", nullable = false, length = 45)) })
	public FactorComplejidadAmbientalId getId() {
		return this.id;
	}

	public void setId(FactorComplejidadAmbientalId id) {
		this.id = id;
	}

	@Column(name = "Valoracion", nullable = false)
	public int getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(int valoracion) {
		this.valoracion = valoracion;
	}

	@Column(name = "factorCalculado", nullable = false)
	public int getFactorCalculado() {
		return this.factorCalculado;
	}

	public void setFactorCalculado(int factorCalculado) {
		this.factorCalculado = factorCalculado;
	}

}
